# Use Anaconda base image
FROM continuumio/anaconda3

# Set working directory
WORKDIR /app

# Copy environment file
COPY environment.yml .

# Create the environment using Conda
RUN conda env create -f environment.yml

# Set environment variables for Conda
ENV CONDA_ENV=docker_data_analysis_prj

# Add the environment to the PATH
ENV PATH /opt/conda/envs/$CONDA_ENV/bin:$PATH

# Copy project files
COPY . .

# Copy dataset folder separately (ensuring it exists)
COPY sample_dataSet /app/sample_dataSet

# Expose the application port (if needed)
EXPOSE 5000

# Use a build argument to specify the environment mode
ARG ENV_MODE=dev
ENV ENV_MODE=$ENV_MODE

# Copy the appropriate .env file
COPY .env.${ENV_MODE} .env

# Run the application with Conda activation
ENTRYPOINT ["/bin/bash", "-c", "source /opt/conda/etc/profile.d/conda.sh && conda activate $CONDA_ENV && python extractImage.py"]